name = "UNM"
author = "UNM"
version = "2.1.2"
description = "Das Modpack für den UNM-Minecraft-Server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37cab2b1e6aee4cdc3ce725c0bf509bdcb4dcbbc7a29968731ffabdaf87723b9"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
