name = "UNM"
author = "UNM"
version = "2.1.0"
description = "Das Modpack für den UNM-Minecraft-Server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fa00ec36bbba0283d0b3841a061f68737bfe43869a200df3ca61a3eb70dca5b1"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
