name = "UNM"
author = "UNM"
version = "2.0.0"
description = "Das Modpack für den UNM-Minecraft-Server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59efa8520296a3b18b10e2843f47137101c181fb6bf766a68f76dfc751cdded4"

[versions]
fabric = "0.15.5"
minecraft = "1.19.2"
