name = "UNM"
author = "UNM"
version = "2.4.0"
description = "Das Modpack für den UNM-Minecraft-Server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b23a9678237d526a6c45c4d5bfdd5cb2f4f1bde2749810febcf19717fc05b3ae"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
