name = "UNM"
author = "UNM"
version = "2.3.0"
description = "Das Modpack für den UNM-Minecraft-Server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e62e48c87e687c82a29a04b9a274d51f2e6d40050116cb38eaf3419a9a11b053"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
