name = "UNM"
author = "UNM"
version = "2.6.0"
description = "Das Modpack für den UNM-Minecraft-Server"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b33ae6c80f8675d090c419aa279aacea570c286e10005b80d3b8499fc80ed2e"

[versions]
fabric = "0.15.6"
minecraft = "1.19.2"
