name = "UNM"
author = "UNM"
version = "3.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6212281eb572695d380c7cd93bd4e439246e9e6c2b94b1b3fc5211761ce21bee"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
