name = "UNM"
author = "UNM"
version = "3.6.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1dce7d708de756413f5c7c2f6daf88e428f3fdefcd7a335e81dffa6cae51679d"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
