name = "UNM"
author = "UNM"
version = "3.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b25375c24ba95202485d592fea9b5497edaf858fed8fbd6f97736db1e439a4ac"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
