name = "UNM"
author = "UNM"
version = "3.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bddafb0e95e1ae228bce28ca107d2cfabde0a2be4809ee91ad6572ce1a1e56ea"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
