name = "UNM"
author = "UNM"
version = "3.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71a23ecfcdffa6a907589ae4c19bfb7b26b7822740d5601ee1b45cbba3df4f69"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
