name = "UNM"
author = "UNM"
version = "3.0.0-alpha.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a27c9fcca1a275f98eabb28715309ea1a5e2f872d27ff0937950738831aa35fc"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
