name = "UNM"
author = "UNM"
version = "3.0.0-alpha.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7f21f560bc19e886e2ad5a3806e260b7368bfbec51742ec7b5d1ff8a1e346e1"

[versions]
forge = "36.2.42"
minecraft = "1.16.5"

[options]
datapack-folder = "config/paxi/datapacks"
