name = "UNM"
author = "UNM"
version = "3.6.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6934c8560e88878ead13f39feeaa9fc8a9add9721983e50e6399755f563238e1"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
