name = "UNM"
author = "UNM"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "619af2344deeec254e26aad0678d3b26a15a6e40018e50c426d6d6d61088ef84"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
