name = "UNM"
author = "UNM"
version = "3.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f22501c918b245b492f7180d23140cc995c4d4b860b559a6a30269844d51a951"

[versions]
forge = "47.3.5"
minecraft = "1.20.1"

[options]
datapack-folder = "config/paxi/datapacks"
