["Turret stats"]
["Turret stats"."Gauss turret"]
#In ticks
#Range: 1 ~ 60
"Fire rate" = 10
#Range: 10.0 ~ 500.0
Health = 500.0
#Range: 0.0 ~ 100.0
Armor = 100.0
#Range: 8.0 ~ 100.0
Range = 100.0
#Range: 1 ~ 100
Damage = 100
