["Soulspring Lamp"]
#Defines items that the Soulspring Lamp can use as fuel
#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
"Fuel Items" = [["cold_sweat:soul_sprout", 1]]
#Defines the dimensions that the Soulspring Lamp can be used in
#Format: ["dimension-id-1", "dimension-id-2", ...etc]
"Valid Dimensions" = ["minecraft:the_nether"]

[Insulation]
#Defines the items that can be used for insulating armor in the Sewing Table
#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
#"cold": The amount of cold insulation the item provides.
#"hot": The amount of heat insulation the item provides.
"Insulation Ingredients" = [
	[
		"minecraft:leather",
		8.0,
		8.0,
	],
	[
		"minecraft:rabbit_hide",
		0.0,
		4.0,
	],
	[
		"cold_sweat:fur",
		8.0,
		0.0,
	],
	[
		"cold_sweat:hoglin_hide",
		0.0,
		8.0,
	],
]
#Defines the items that provide insulation when worn
#Format: [["item_id", cold, hot], ["item_id", cold, hot], ...etc]
#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
#"cold": The amount of cold insulation the item provides.
#"hot": The amount of heat insulation the item provides.
"Insulating Armor" = [
	[
		"minecraft:leather_helmet",
		32.0,
		32.0,
	],
	[
		"minecraft:leather_chestplate",
		64.0,
		64.0,
	],
	[
		"minecraft:leather_leggings",
		64.0,
		64.0,
	],
	[
		"minecraft:leather_boots",
		32.0,
		32.0,
	],
	[
		"cold_sweat:fur_cap",
		32.0,
		0.0,
	],
	[
		"cold_sweat:fur_parka",
		64.0,
		0.0,
	],
	[
		"cold_sweat:fur_pants",
		64.0,
		0.0,
	],
	[
		"cold_sweat:fur_boots",
		32.0,
		0.0,
	],
	[
		"cold_sweat:hoglin_headpiece",
		0.0,
		32.0,
	],
	[
		"cold_sweat:hoglin_tunic",
		0.0,
		64.0,
	],
	[
		"cold_sweat:hoglin_trousers",
		0.0,
		64.0,
	],
	[
		"cold_sweat:hoglin_hooves",
		0.0,
		32.0,
	],
	[
		"mekanism:mekasuit_helmet",
		1024.0,
		1024.0,
	],
	[
		"mekanism:mekasuit_bodyarmor",
		1024.0,
		1024.0,
	],
	[
		"mekanism:mekasuit_pants",
		1024.0,
		1024.0,
	],
	[
		"mekanism:mekasuit_boots",
		1024.0,
		1024.0,
	],
]
#Defines how many insulation slots armor pieces have
#Format: [head, chest, legs, feet]
"Insulation Slots" = [32, 64, 64, 32]
#Defines insulation items that have the special "chameleon molt" effect
#Format: [["item_id", insulation, adaptSpeed], ["item_id", insulation, adaptSpeed], ...etc]
#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
#"insulation": The amount of insulation the item provides. Will adjust to hot/cold based on the environment.
#"adaptSpeed": The speed at which the item adapts to the current temperature. Higher values mean faster adaptation (from 0 to 1).
"Adaptive Insulation Ingredients" = [
	[
		"cold_sweat:chameleon_molt",
		8.0,
		0.0085,
	],
	[
		"#minecraft:wool",
		16.0,
		1.0,
	],
]
